{% set version = "2.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mbsts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mbsts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mbsts/mbsts_{{ version }}.tar.gz
  sha256: ab4547397754fe6663ae5b61a80e87555304df488510f0e69d701f61e4fe511f

build:
  merge_build_host: true  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kfas
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-pscl
  run:
    - r-base
    - r-kfas
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-pscl

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mbsts')"           # [not win]
    - "\"%R%\" -e \"library('mbsts')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=mbsts
  summary: Multivariate time series regression using dynamic linear models fit by MCMC. See Qiu, Jammalamadaka and Ning (2018) <http://www.jmlr.org/papers/volume19/18-009/18-009.pdf>.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - melonhead901
    - conda-forge/r

# The original CRAN metadata for this package was:

# Package: mbsts
# Type: Package
# Title: Multivariate Bayesian Structural Time Series
# Version: 1.0
# Author: Jinwen Qiu <qjwsnow_ctw@hotmail.com>
# Maintainer: Jinwen Qiu <qjwsnow_ctw@hotmail.com>
# Description: Multivariate time series regression using dynamic linear models fit by MCMC. See Qiu, Jammalamadaka and Ning (2018) <http://www.jmlr.org/papers/volume19/18-009/18-009.pdf>.
# License: LGPL-2.1
# NeedsCompilation: no
# Depends: pscl, MASS, KFAS, MCMCpack, Matrix, R(>= 3.5)
# Repository: CRAN
# Date: 2020-01-07
# Packaged: 2020-01-08 03:05:45 UTC; william
# Date/Publication: 2020-01-09 18:10:05 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
