{% set version = "3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mbsts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mbsts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mbsts/mbsts_{{ version }}.tar.gz
  sha256: 0a26cb6626e6e10f69c46bddd971a2e2ca5e4e0c2d4e2c14cd06cb001539eb61

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bbmisc
    - r-kfas
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-ggplot2
    - r-matrixstats
    - r-pscl
    - r-reshape2
  run:
    - r-base
    - r-bbmisc
    - r-kfas
    - r-mass
    - r-mcmcpack
    - r-matrix
    - r-ggplot2
    - r-matrixstats
    - r-pscl
    - r-reshape2

test:
  commands:
    - $R -e "library('mbsts')"           # [not win]
    - "\"%R%\" -e \"library('mbsts')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mbsts
  summary: Multivariate time series regression using dynamic linear models fit by MCMC. See Qiu, Jammalamadaka and Ning (2018) <http://www.jmlr.org/papers/volume19/18-009/18-009.pdf>.
  license: LGPL-2.1-only
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r

# The original CRAN metadata for this package was:
# Package: mbsts
# Type: Package
# Title: Multivariate Bayesian Structural Time Series
# Version: 1.0
# Author: Jinwen Qiu <qjwsnow_ctw@hotmail.com>
# Maintainer: Jinwen Qiu <qjwsnow_ctw@hotmail.com>
# Description: Multivariate time series regression using dynamic linear models fit by MCMC. See Qiu, Jammalamadaka and Ning (2018) <http://www.jmlr.org/papers/volume19/18-009/18-009.pdf>.
# License: LGPL-2.1
# NeedsCompilation: no
# Depends: pscl, MASS, KFAS, MCMCpack, Matrix, R(>= 3.5)
# Repository: CRAN
# Date: 2020-01-07
# Packaged: 2020-01-08 03:05:45 UTC; william
# Date/Publication: 2020-01-09 18:10:05 UTC
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
